{% set name = "sphinx-jinja2-compat" %}
{% set version = "0.2.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_jinja2_compat-{{ version }}.tar.gz
  sha256: 974289a12a9f402108dead621e9c15f7004e945d5cfcaea8d6419e94d3fa95a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - whey >=0.0.20
    - whey-pth >=0.0.4
  run:
    - jinja2 >=2.10
    - markupsafe >=1
    - python >=3.6

test:
  imports:
    - sphinx_jinja2_compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sphinx-toolbox/sphinx-jinja2-compat
  summary: Patches Jinja2 v3 to restore compatibility with earlier Sphinx versions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - domdfcoding
